input {
  beats {
    port => 5044
  }
}

filter {
  if [fields][log_type] == "apache_access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    mutate {
      convert => {
        "bytes"    => "integer"
        "response" => "integer"
      }
    }
    date {
      match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
      remove_field => ["timestamp"]
    }
    if [response] {
      if [response] >= 500 {
        mutate { add_field => { "status_category" => "5xx Server Error" } }
      } else if [response] >= 400 {
        mutate { add_field => { "status_category" => "4xx Client Error" } }
      } else if [response] >= 200 {
        mutate { add_field => { "status_category" => "2xx Success" } }
      }
    }
    geoip {
      source => "clientip"
      target => "geoip"
    }
  }
}

output {
  elasticsearch {
    hosts    => ["https://localhost:9200"]
    user     => "elastic"
    password => "<SUA-SENHA>"
    index    => "apache-logs-%{+YYYY.MM.dd}"
    ssl_enabled => true
    ssl_verification_mode => none
  }
}